(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/,emacs.d/elisp/ac-dict")
(define-key ac-mode-map (kbd "M-/") 'auto-complete)
(ac-config-default)
(setq ac-auto-start nil)
(define-key ac-complete-mode-map "\C-n" 'ac-next)
(define-key ac-complete-mode-map "\C-p" 'ac-previous)
