;(require 'jaspace)
;(setq jaspace-alternate-jaspace-string "□")
;(setq jaspace-alternate-eol-string "\u21B5\n")
;(setq jaspace-highlight-tabs ?\xBB)

;(require 'whitespace)
;(setq whitespace-style 
;	'(face tabs tab-mark spaces space-mark newline newline-mark))
;(setq whitespace-display-mappings '(
;	(space-mark ?\u3000 [?\u25a1])
;	(tab-mark ?\t [?\xBB ?\t] [?\\ ?\t])
;;	(newline-mark ?\n [?\u21B5 ?\n] [?$ ?\n])
;	(newline-mark ?\n [?\u2193 ?\n] [?$ ?\n])
;))
;(setq whitespace-space-regexp "\\([\u3000]+\\)")
;(set-face-foreground 'whitespace-tab "#adff2f")
;(set-face-background 'whitespace-tab 'nil)
;(set-face-foreground 'whitespace-space "#7cfc00")
;(set-face-background 'whitespace-space 'nil)
;(set-face-foreground 'whitespace-newline "#229922")
;(set-face-background 'whitespace-newline 'nil)
;(set-face-bold-p 'whitespace-space t)
;(global-whitespace-mode 1)
;(global-set-key (kbd "C-x w") 'global-whitespace-mode)
